id: A5633CB5C
title: The Mountain Smoke Offering Arranged for Recitation
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.304734
  last_modified_at: 2022-03-01 05:41:22.304736
