id: A5633CB5C
title: Short Sang Offering to KurukullÄ
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.295501
  last_modified_at: 2022-03-01 05:41:22.295504
