id: A5633CB5C
title: Brief Smoke Offering to the Great Lion of the World
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.286064
  last_modified_at: 2022-03-01 05:41:22.286068
