id: A5633CB5C
title: The Mountain Smoke Offering (Riwo Sangchö)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.301481
  last_modified_at: 2022-03-01 05:41:22.301484
