id: A5633CB5C
title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great Master
  Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.288155
  last_modified_at: 2022-03-01 05:41:22.288188
