id: A5633CB5C
title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
  All Obstacles on the Path'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.298225
  last_modified_at: 2022-03-01 05:41:22.298228
