id: A5633CB5C
title: Yarlha Shampo Sang Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.306144
  last_modified_at: 2022-03-01 05:41:22.306147
