id: A5633CB5C
title: Sang Offering to Yellow Jambhala
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.294447
  last_modified_at: 2022-03-01 05:41:22.294449
