id: A5633CB5C
title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.293331
  last_modified_at: 2022-03-01 05:41:22.293334
