id: A5633CB5C
title: A Concise Sang Offering to Tārā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:41:22.282524
  last_modified_at: 2022-03-01 05:41:22.282531
